// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiwmusrmmtjoinmepxgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpd211c3JtbXRqb2lubWVweGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjY2NDMsImV4cCI6MjA1OTk0MjY0M30.MNqctqp_0l0OSpNXrpYfxuZycMfKiMeOMyfFhVm7QCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);